layihe/Models/Pilot.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace layihe.Models
{
    public class Pilot
    {
        public int PilotId { get; set; }
        public string PilotName { get; set; }
        public string ImagePath { get; set; }
    }
}

layihe/Controllers/PilotController.cs
using layihe.BLL.PilotBLL;
using layihe.Dtos.PilotDtos;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace layihe.Controllers
{
    public class PilotController : Controller
    {
        private readonly IPilotServices _pilotServices;
        private readonly IWebHostEnvironment _environment;
        public PilotController(IPilotServices pilotServices, IWebHostEnvironment webHostEnvironment)
        {
            _pilotServices = pilotServices;
            _environment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _pilotServices.Get());
        }
        public IActionResult Registration()
        {
            return View();
        }
        public async Task<IActionResult> Add([FromForm] PilotToAddDto pilottoadddto)
        {
            try
            {
                var originalFileName = pilottoadddto.ImagePath.FileName;
                string fileExtension = pilottoadddto.ImagePath.FileName.Substring(pilottoadddto.ImagePath.FileName.LastIndexOf('.') + 1);
                Guid guid = Guid.NewGuid();
                var uploads = Path.Combine(_environment.WebRootPath, "files");
                string fileName = guid.ToString() + "-fileName-" + pilottoadddto.ImagePath.FileName;
                string filePath = "/" + fileName;
                if (!Directory.Exists(Path.Combine(uploads)))
                    Directory.CreateDirectory(Path.Combine(uploads));

                if (pilottoadddto.ImagePath.Length > 0)
                {
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                    {
                        await pilottoadddto.ImagePath.CopyToAsync(fileStream);
                    }
                }
                await _pilotServices.Addsync(pilottoadddto, fileName);

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

        }

    }

   }

layihe/Views/Pilot/Index.cshtml
@using layihe.Dtos.PilotDtos
@model List<PilotToListDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .pilot-container {
        position: relative !important;
        background-image: url("../pilotbackground.jfif");
        width: 100% !important;
        height: 101% !important;
        background-size: cover;
        background-position: center;
    }
.pilots{
    margin-left:0px!important;
    margin-right:0px!important;
}
    .btn {
        margin: 15px 0 15px 15px;
        color: whitesmoke;
        border-color: whitesmoke;
        font-weight: bolder;
    }
    .pilot-container .card-text {
        text-align: center;
        color: dodgerblue;
        font-size: 20px;
        font-weight: bolder;
    }
    }
</style>

@{ 
    int i = 0;
}
<div class="pilot-container">
  <a asp-controller="Pilot" asp-action="Registration" class="btn btn-outline-primary">Add</a>

    <div class="row pilots">
        @foreach (var p in Model)
        {
            if (i > 0 && i % 3 == 0)
            {
                @:<div class="row" style="margin-top:20px"> </div>
            }
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="/files/@p.ImagePath" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text">@p.PilotName.</p>
                    </div>
                </div>
            </div>
            i++;

        }
    </div>
</div>

layihe/Views/Pilot/Registration.cshtml
@using layihe.Dtos.PilotDtos
@model PilotToAddDto

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .registration {
        position: absolute;
        background-color: #F3F6F9 !important;
        padding: 40px;
        margin-left: 300px;
        margin-top: 70px;
        color: #009CFF !important;
        font-size: 18px;
    }
   
    .registration button {
        color: white;
        margin-top: 15px;
        float: right;
        background-color: #009CFF!important;
        border-color: #009CFF!important;
    }

    .registr-container {
        position: relative !important;
        background-image: url("../registrbackground.jpg");
        width: 100% !important;
        height: 101% !important;
        background-size: cover;
        background-position: center;
    }
</style>
<div class="registr-container">
    <div class="registration">
        <form asp-controller="Pilot" asp-action="Add" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="name" class="form-label">Pilot Name</label>
                <input type="text" class="form-control" id="id" asp-for="PilotName" placeholder="Enter name">
            </div>
            <div class="mb-3">
                <label for="imagePath" class="form-label">ImagePath</label>
                <input type="file" class="form-control" id="id" asp-for="ImagePath">
            </div>
            <button type="submit" class="btn btn-primary">Add</button>

        </form>
    </div>
</div>