layihe/Controllers/FlightController.cs
using AutoMapper;
using layihe.BLL.FlightBLL;
using layihe.BLL.PassengerBLL;
using layihe.BLL.TicketBLL;
using layihe.Dtos;
using layihe.Dtos.FlightDtos;
using layihe.Dtos.PassengerDtos;
using layihe.Dtos.TicketDtos;
using layihe.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rotativa;
namespace layihe.Controllers
{
    public class FlightController : Controller
    {
        private readonly IFlightServices _flightServices;
        private readonly ITicketServices _ticket;
        private readonly IPassengerServices _passenger;
        private readonly IMapper _mapper;
        public FlightController(IFlightServices flightServices,ITicketServices ticket,IPassengerServices passenger,IMapper mapper)
        {
            _flightServices = flightServices;
            _ticket = ticket;
            _passenger = passenger;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _flightServices.Get());
        }
      
        public async Task<IActionResult> Registration()
        {
            
            return View(await _flightServices.InnerModel());
        }
        public async Task<IActionResult> Add(FlightToAddDto flightToAddDto)
        {
            await _flightServices.Addasync(flightToAddDto);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Search( )
        {
         return View(await _flightServices.InnerModel());
        }
        public async Task<IActionResult> Find(FlightToAddDto flightToAddDto)
        {
            try
            {
                if (flightToAddDto.DepartureCityId != 0 && flightToAddDto.ArrivialCityId != 0 && flightToAddDto.DepartureTime !=null)
                {
                    var flight = await _flightServices.Find(flightToAddDto.DepartureCityId, flightToAddDto.ArrivialCityId,(flightToAddDto.DepartureTime).ToShortDateString());
                    if (flight.Count == 0)
                    {
                        return RedirectToAction("DontFindFlight",new { id = flightToAddDto.DepartureCityId });
                    }
                    else
                    {
                        return View(flight);
                    }
                }
                else
                {
                  return RedirectToAction("DontFindFlight");

                }
            }
            catch(Exception ex)
            {
                return View(BadRequest(ex.Message));
            }
        }
        public async Task<IActionResult> DontFindFlight(int id)
        {
            return View(await _flightServices.Get(id));
        }

        public  IActionResult RegisterPassenger(int id)
        {
            try
            {
                TempData["flightId"] = id;
                return View();
            }
            catch(Exception ex)
            {
                return View(BadRequest(ex.Message));
            }
        }
        public  async Task<IActionResult> SellTicket(TicketToAddDto ticketToAddDto)
        {
            Random rd = new Random();
                try
                {
                 await _passenger.Addsync(ticketToAddDto.Passenger);
                ticketToAddDto.NewFlightId =Convert.ToInt32(TempData["flightId"]);
                ticketToAddDto.TicketNumber = rd.Next(100000000, 999999999);
                
                await _ticket.Addsync(ticketToAddDto);
                return View("TicketImage",ticketToAddDto);
            }
            catch(Exception ex)
            {
                return View(BadRequest(ex.Message));
            }
        }

        public async Task<IActionResult> TicketImage()
        {
            return View();
        }
      public async Task<IActionResult> FlightCancel(int id)
        {
            await _flightServices.Delete(id);
            return RedirectToAction("Index");
        }
      public async Task<IActionResult> Info(int id)
        {
            return View(await _flightServices.GetFlight(id));

        }
    }
}

layihe/Views/Flight/DontFindFlight.cshtml
@using layihe.Dtos.FlightDtos
@model List<FlightToListDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .flightIndex {
        margin-left: 120px !important;
    }

        .flightIndex .table {
            background-color: whitesmoke;
            color: dodgerblue;
            text-align: center;
        }

        .flightIndex .btn {
            float: right !important;
            margin: 15px 0 15px 15px;
        }

    .table {
        --bs-table-striped-bg: lavender;
        --bs-table-striped-color: dodgerblue;
    }
    #dontflighth1{
        text-align:center;
        padding-top:40px;
        color:floralwhite;
        
    }
</style>
<div class="city">

    <h1 id="dontflighth1" >Don't Find Flight</h1>

    <div style="position:absolute" class="flightIndex">
        <a href="/Flight/Search" class="btn btn-primary">Search</a>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Departure Time</th>
                    <th>Arrivial Time</th>
                    <th>Capacity</th>
                    <th>Seating Capacity</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var f in Model)
                {


                    @if (f.DepartureTime >= DateTime.Now)
                    {
                        <tr>
                            <td>@f.DepartureCity.DepName</td>
                            <td>@f.ArrivialCity.Name</td>
                            <td>@f.DepartureTime</td>
                            <td>@f.ArrivialTime</td>
                            <td>@f.Capacity</td>
                            <td>@f.SeatingCapacity</td>
                            <td>@f.Price</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

layihe/Views/Flight/Find.cshtml
@using layihe.Dtos.FlightDtos
@model List<FlightToListDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .flightfind {
        position: relative !important;
        background-image: url("../flihgtsearchbackground.jpg");
        width: 100% !important;
        height: 100% !important;
        position: relative;
        background-size: cover;
        background-position: center;
    }
    .flightIndex {
        margin:45px 10px 0 100px!important
    }

        .flightIndex .table {
            background-color: whitesmoke;
            color: dodgerblue;
            text-align: center;
        }
    .table {
        --bs-table-striped-bg: lavender;
        --bs-table-striped-color: dodgerblue;
    }
    .flightIndex .changesearchbtn {
        float:right;
        margin-bottom: 10px;
        font-weight: bold;
        font-size: 20px;
        background-color: whitesmoke;
        border-color: dodgerblue;
        color: dodgerblue;
    }
    
</style>
<div class="flightfind">


    <div style="position:absolute" class="flightIndex">
   <a class="btn changesearchbtn" asp-controller="Flight" asp-action="Search">Change Search</a>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Departure Time</th>
                    <th>Arrivial Time</th>
                    <th>Capacity</th>
                    <th>Seating Capacity</th>
                    <th>Price</th>
                    <th>Sell Ticket</th>
                    <th>Details</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var f in Model)
                {


                    @if (f.DepartureTime >= DateTime.Now)
                    {
                        <tr>
                            <td>@f.DepartureCity.DepName</td>
                            <td>@f.ArrivialCity.Name</td>
                            <td>@f.DepartureTime.ToString("dd/MM/yyyy HH:mm")</td>
                            <td>@f.ArrivialTime.ToString("dd/MM/yyyy HH:mm")</td>
                            <td>@f.Capacity</td>
                            <td>@f.SeatingCapacity</td>
                            <td>@f.Price</td>
                            @if (f.SeatingCapacity != 0)
                            {
                            <td>@Html.ActionLink("Sell", "RegisterPassenger", "Flight", new { id = f.NewFlightId }, new { @class = "btn btn-primary" })</td>
                            }
                            else
                            {
                              <button class="disabled btn-primary">Sell</button>
                            }

                            <td>@Html.ActionLink("Detail", "Info", "Flight", new { id = f.NewFlightId }, new { @class = "btn btn-success" })</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

layihe/Views/Flight/Index.cshtml
@using layihe.Dtos.FlightDtos
@model List<FlightToListDto> 
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .flightIndex {
        margin-left: 60px !important;
        margin-right:10px;
    }

        .flightIndex .table {
            background-color: whitesmoke;
            color: dodgerblue;
            text-align: center;
        }

        .flightIndex .btn-primary {
            float: right !important;
            margin: 15px 0 15px 15px;
        }

    .table {
        --bs-table-striped-bg: lavender;
        --bs-table-striped-color: dodgerblue;
    }
</style>
<div class="city">
    

    <div style="position:absolute" class="flightIndex">
        <a href="/Flight/Registration" class="btn btn-primary">Add</a>
        <a href="/Flight/Search" class="btn btn-primary">Search</a>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Departure Time</th>
                    <th>Arrivial Time</th>
                    <th>Capacity</th>
                    <th>Seating Capacity</th>
                    <th>Price</th>
                    <th></th>
                    <th></th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var f in Model)
                {


                    @if (f.DepartureTime >= DateTime.Now)
                    {
                <tr>
                    <td>@f.DepartureCity.DepName</td>
                    <td>@f.ArrivialCity.Name</td>
                    <td>@f.DepartureTime.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@f.ArrivialTime.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@f.Capacity</td>
                    <td>@f.SeatingCapacity</td>
                    <td>@f.Price</td>
                    @if ((f.Capacity - f.SeatingCapacity) < f.SeatingCapacity)
                    {
                        <td>@Html.ActionLink("Cancel Flight", "FlightCancel", "Flight", new { id = f.NewFlightId }, new { @class = "btn btn-danger" })</td>
                    }
                    else
                    {
                        <td><button class="disabled">Cancel Flight</button></td>
                    }
                    <td>@Html.ActionLink("Detail", "Info", "Flight", new { id = f.NewFlightId }, new { @class = "btn btn-success" })</td>

                </tr>
                    }

            }
                </tbody>
            </table>
    </div>

</div>

layihe/Views/Flight/Info.cshtml
@using layihe.Dtos.FlightDtos
@model FlightToListDto
@{
    ViewData["Title"] = "Info";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .detail-container {
        position: relative !important;
        background-image: url("/detailsbackground.jpg");
        width: 100% !important;
        height: 101% !important;
        background-size: cover;
        background-position: center;
    }

        .detail-container .flightIndex {
            position:absolute;
            left: 50%;
            transform: translate(-50%);
            width: 70%;
            top: 20%;
        }

     .detail-container   .flightIndex .table {
            background-color: whitesmoke;
            text-align: center;
            margin-top:35px;
        }
     .detail-container .flightIndex .table tr{
         color:slategray;
     }
        .detail-container .table th {
            color: darkblue;
        }
    .table {
        --bs-table-striped-bg: lavender;
        --bs-table-striped-color: dodgerblue;
    }
</style>
<div class="detail-container">
    <div  class="flightIndex">
       
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Departure Time</th>
                    <th>Arrivial Time</th>
                    <th>Capacity</th>
                    <th>Seating Capacity</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody> 
                        <tr>
                            <td>@Model.DepartureCity.DepName</td>
                            <td>@Model.ArrivialCity.Name</td>
                            <td>@Model.DepartureTime.ToString("dd/MM/yyyy HH:mm")</td>
                            <td>@Model.ArrivialTime.ToString("dd/MM/yyyy HH:mm")</td>
                            <td>@Model.Capacity</td>
                            <td>@Model.SeatingCapacity</td>
                            <td>@Model.Price</td>
                
                        </tr>
            </tbody>
        </table>
    </div>

</div>

layihe/Views/Flight/RegisterPassenger.cshtml
@using layihe.Dtos.TicketDtos
@model TicketToAddDto
@{
    ViewData["Title"] = "RegisterPassenger";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .passengerregistr-container {
        position: relative!important;
        background-image: url("/registrbackground.jpg");
        width: 100% !important;
        height: 101% !important;
        background-size: cover;
        background-position: center;
    }

        .passengerregistr-container .registration {
            position: absolute;
            margin-left: 290px;
            margin-top: 80px;
            color: white;
            font-size: 18px;
            font-weight: bolder;
        }
            .passengerregistr-container .registration .btn {
                background-color: darkblue;
                width: 50%;
                border-color:darkblue;
            }
</style>
<div class="passengerregistr-container">
    <div class="registration">
        <form asp-controller="Flight" asp-action="SellTicket" method="post">
            <div style="float:left">
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" asp-for="Passenger.PassengerName" class="form-control" placeholder="Enter Name" />
            </div>
            <div class="mb-3">
                <label for="name" class="form-label">Surname</label>
                <input type="text" asp-for="Passenger.PassengerSurname" class="form-control" placeholder="Enter Surname" />
            </div>
            <div class="mb-3">
                <label for="genrename" class="form-label">BirthDate</label>
                <input type="date" class="form-control" asp-for="Passenger.BirthDate">
            </div>
                </div>
            <div style="float:left;margin-left:20px">
            <div class="mb-3">
                <label for="genrename" class="form-label">Pasport Number</label>
                <input type="text" class="form-control" id="id" asp-for="Passenger.PasportNumber" placeholder="Enter PasportNumber">
            </div>
            <div class="mb-3">
                <label for="genrename" class="form-label">Phone</label>
                <input type="text" class="form-control" id="id" asp-for="Passenger.PhoneNumber" placeholder="Enter PhoneNmber">
            </div>
            <div class="mb-3">
                <label for="genrename" class="form-label">Email</label>
                <input type="email" class="form-control" id="id" asp-for="Passenger.Email" placeholder="Enter Email">
            </div>
            <input type="submit" name="name" value="Sell" class="btn btn-primary" style="float:right" />
             </div>
        </form>
    </div>
</div>

layihe/Views/Flight/Registration.cshtml
@using layihe.Dtos.FlightDtos
@model FlightToAddDto

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .registration {
        position: absolute;
        background-color: whitesmoke;
        padding: 40px;
        margin-left: 240px;
        margin-top: 70px;
        }

        .registration button {
            margin-top: 31px;
        }
    .registr-container {
        position: relative !important;
        background-image: url("../registrbackground.jpg");
        width: 100% !important;
        height: 101% !important;
        background-size: cover;
        background-position: center;
    }
</style>
<div class="registr-container">
<div class="registration">
    <form asp-controller="Flight" asp-action="Add" method="post">
        <div style="float:left">
            <div class="mb-3">
                <label for="name" class="form-label">DepartureCity Name</label>
                <select class="form-control" asp-for="DepartureCityId" asp-items="@(new SelectList(Model.DepartureCities,"Id","DepName"))"></select>
            </div>
            <div class="mb-3">
                <label for="name" class="form-label">ArrivialCity Name</label>
                <select class="form-control" asp-for="ArrivialCityId" asp-items="@(new SelectList(Model.ArrivialCities,"ArrivialCityId","Name"))"></select>
            </div>

            <div class="mb-3">
                <label for="genrename" class="form-label">DepartureTime</label>
                <input type="datetime-local" class="form-control" id="id" asp-for="DepartureTime" placeholder="Enter ArrivialTime">
            </div>
            <div class="mb-3">
                <label for="genrename" class="form-label">ArrivialTime</label>
                <input type="datetime-local" class="form-control" id="id" asp-for="ArrivialTime" placeholder="Enter ArrivialTime">
            </div>
        </div>
        <div style="float:left;margin-left:40px">
            <div class="mb-3">
                <label for="genrename" class="form-label">Capacity</label>
                <input type="text" class="form-control" id="id" asp-for="Capacity" placeholder="Enter Capacity">
            </div>
            <div class="mb-3">
                <label for="genrename" class="form-label">SeatingCapacity</label>
                <input type="text" class="form-control" id="id" asp-for="SeatingCapacity" placeholder="Enter Capacity">
            </div>
            <div class="mb-3">
                <label for="genrename" class="form-label">Price</label>
                <input type="text" class="form-control" id="id" asp-for="Price" placeholder="Enter Price">
            </div>
            <button type="submit" class="btn btn-primary">Save Flight</button>
        </div>

    </form>
    </div>
    </div>

layihe/Views/Flight/Search.cshtml
@using layihe.Dtos.FlightDtos
@model FlightToAddDto

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .searchflight {
        position: absolute;
        background-color: unset;
        padding: 25px;
        margin-left: 80px;
        margin-top: 30px;
        text-align:center!important;
        font-size:30px;
        color:ghostwhite;
    }

    .searchflight button {
        margin-top: 52px;
        width:150px!important;
    }

    .searchflight-container {
        position: relative !important;
        background-image: url("../search-background.jpg");
        width: 100% !important;
        height: 101% !important;
        background-size: cover;
        background-position: center;
    }
    .searchflight-container .mb-3{
        float:left!important;
        margin-right:15px;
    }
    .searchflight .form-control{
        background-color:white!important;
    }
</style>

<div class="searchflight-container">
    <div class="searchflight">
        <form asp-controller="Flight" asp-action="Find" method="post">
                <div class="mb-3" >
                    <label for="depname" class="form-label">DepartureCity Name</label>
                 <select class="form-control"  asp-for="DepartureCityId" asp-items="@(new SelectList(Model.DepartureCities,"Id","DepName"))"></select>
                </div>
                <div class="mb-3">
                    <label for="arrname" class="form-label">ArrivialCity Name</label>
                    <select class="form-control"   asp-for="ArrivialCityId" asp-items="@(new SelectList(Model.ArrivialCities, "ArrivialCityId", "Name"))"></select>
                </div>
                <div class="mb-3">
                    <label for="deptime" class="form-label">DepartureTime</label>
                    <input type="date" value="dd/mm/yyyy"  class="form-control"   asp-for="DepartureTime" />
                </div>
                <div class="mb-3">
                <button type="submit" class="btn btn-primary">Search</button>
                </div>
        </form>
    </div>
</div>

layihe/Views/Flight/TicketImage.cshtml
@{
    ViewData["Title"] = "TicketImage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using layihe.Dtos.TicketDtos
@model TicketToAddDto
<style>
    .ticket {
        position: relative !important;
        background-image: url("../ticktbackground.jpg");
        width: 100% !important;
        height: 100% !important;
        position: relative;
        background-size: cover;
        background-position: center;
        padding-top:40px;
    }
    .ticket label{
        width:100px;
    }
    .ticket .table{
        margin-bottom:50px;
        color:whitesmoke;
    }
        .ticket .btn {
            background-color: darkblue;
            border-color: darkblue;
            float: right;
            width: 15%;
            margin-right: 10px;
            font-size: 25px;
            margin-top: 210px;
        }
</style>
<div class="ticket">
    <table class="table">
        <thead>
         <th>Name</th>
         <th>Surname</th>
         <th>Passport Nmber</th>
         <th>Phone</th>
         <th>Email</th>
         <th>Ticket number</th>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Passenger.PassengerName</td>
                <td>@Model.Passenger.PassengerSurname</td>
                <td>@Model.Passenger.PasportNumber</td>
                <td>@Model.Passenger.PhoneNumber</td>
                <td>@Model.Passenger.Email</td>
                <td>@Model.TicketNumber</td>
               
            </tr>
        </tbody>
    </table>
 <table class="table">
     <thead>
         <th>From</th>
         <th>Departure Time</th>
         <th>To</th>
         <th>Arrivial Time</th>
         <th>Price</th>
     </thead>
     <tbody>
         <tr>

             <td>@Model.NewFlight.DepartureCity.DepName</td>
             <td>@Model.NewFlight.DepartureTime.ToString("dd/MM/yyyy HH:mm")</td>
             <td>@Model.NewFlight.ArrivialCity.Name</td>
             <td>@Model.NewFlight.ArrivialTime.ToString("dd/MM/yyyy HH:mm")</td>
             <td>@Model.NewFlight.Price</td>
         </tr>
     </tbody>
 </table>
 <button class="btn btn-primary">Print</button>
</div>